name: tracer
description: A modern, simple and easy-to-implement logging framework for Dart.
version: 0.3.0
repository: https://github.com/JHubi1/tracer

topics:
  - logging
  - tracer
  - error

environment:
  sdk: ^3.5.3

dependencies:
  intl: ^0.20.1
  stack_trace: ^1.12.0
  web: ^1.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
