name: tracer
description: A modern, simple and easy-to-implement logging framework for Dart.
version: 0.1.0
repository: https://github.com/JHubi1/tracer

environment:
  sdk: ^3.5.3

dependencies:
  intl: ^0.19.0
  event: ^3.1.0
  stack_trace: ^1.12.0
  timezone: ^0.9.4
  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
